# Generated by Django 5.2 on 2025-07-28 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proveedorproducto',
            unique_together={('proveedor', 'producto')},
        ),
    ]
