# Generated by Django 5.2 on 2025-08-12 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0001_initial'),
        ('proveedores', '0002_proveedor_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedorproducto',
            name='negocio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_productos', to='negocios.tblnegocio'),
        ),
    ]
