# Generated by Django 5.2 on 2025-08-12 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='negocio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='negocios.tblnegocio'),
        ),
    ]
