# Generated by Django 5.2 on 2025-08-08 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoNegocio', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'tipo negocio',
                'verbose_name_plural': 'tipo negocios',
            },
        ),
        migrations.CreateModel(
            name='TblNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreNegocio', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=255)),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('propietario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negocio_propietario', to=settings.AUTH_USER_MODEL)),
                ('tipoNegocio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='negocios.tiponegocio')),
            ],
        ),
    ]
