# Generated by Django 5.2 on 2025-08-03 15:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0002_usuarionegocio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuarionegocio',
            unique_together={('usuario', 'negocio')},
        ),
    ]
